### ISSUE TITLE
does nt work anymore

### ISSUE THREAD

**Issue by Onlineraider** [Z2r-YT/Infinite-Craft-Cheat#1]
the items will not appeat

**Comment by Z2r-YT** [comment]
Fixed! thanks for reporting.

**Comment by Onlineraider** [comment]
still does not work for me. used the updated script  from the github that was changed 1 hour ago
